[tasks.update]
description = "Update nixos"
usage = """
flag "--switch" help="Switch immediately (default: stage for next boot)"
"""
run = """
#!/usr/bin/env bash
set -e
nix flake update
git commit -am "flake update"
if [[ $usage_switch == true ]]; then
  sudo nixos-rebuild switch --flake .
else
  sudo nixos-rebuild boot --flake .
fi
"""

[tasks.switch]
description = "Switch immediately to previously-staged update"
run = "sudo nixos-rebuild switch --flake ."
